/*

package com.ruoyi.web.controller.tool.entity.webServiceUtils;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


*/
/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 *
 *//*

@WebService(name = "ZhsfService", targetNamespace = "http://webservice.data.com/")
@XmlSeeAlso({
        ObjectFactory.class
})
public interface ZhsfService {


    */
/**
     *
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     *//*

    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findSignal", targetNamespace = "http://webservice.data.com/", className = "com.FindSignal")
    @ResponseWrapper(localName = "findSignalResponse", targetNamespace = "http://webservice.data.com/", className = "com.FindSignalResponse")
    @Action(input = "http://webservice.data.com/ZhsfService/findSignalRequest", output = "http://webservice.data.com/ZhsfService/findSignalResponse")
    public String findSignal(
            @WebParam(name = "arg0", targetNamespace = "")
                    String arg0,
            @WebParam(name = "arg1", targetNamespace = "")
                    String arg1,
            @WebParam(name = "arg2", targetNamespace = "")
                    String arg2);

    */
/**
     *
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     *//*

    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findStore", targetNamespace = "http://webservice.data.com/", className = "com.FindStore")
    @ResponseWrapper(localName = "findStoreResponse", targetNamespace = "http://webservice.data.com/", className = "com.FindStoreResponse")
    @Action(input = "http://webservice.data.com/ZhsfService/findStoreRequest", output = "http://webservice.data.com/ZhsfService/findStoreResponse")
    public String findStore(
            @WebParam(name = "arg0", targetNamespace = "")
                    String arg0,
            @WebParam(name = "arg1", targetNamespace = "")
                    String arg1,
            @WebParam(name = "arg2", targetNamespace = "")
                    String arg2);

    */
/**
     *
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     *//*

    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findWaterRz", targetNamespace = "http://webservice.data.com/", className = "com.FindWaterRz")
    @ResponseWrapper(localName = "findWaterRzResponse", targetNamespace = "http://webservice.data.com/", className = "com.FindWaterRzResponse")
    @Action(input = "http://webservice.data.com/ZhsfService/findWaterRzRequest", output = "http://webservice.data.com/ZhsfService/findWaterRzResponse")
    public String findWaterRz(
            @WebParam(name = "arg0", targetNamespace = "")
                    String arg0,
            @WebParam(name = "arg1", targetNamespace = "")
                    String arg1,
            @WebParam(name = "arg2", targetNamespace = "")
                    String arg2);

    */
/**
     *
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     *//*

    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findWaterAlwtlv", targetNamespace = "http://webservice.data.com/", className = "com.FindWaterAlwtlv")
    @ResponseWrapper(localName = "findWaterAlwtlvResponse", targetNamespace = "http://webservice.data.com/", className = "com.FindWaterAlwtlvResponse")
    @Action(input = "http://webservice.data.com/ZhsfService/findWaterAlwtlvRequest", output = "http://webservice.data.com/ZhsfService/findWaterAlwtlvResponse")
    public String findWaterAlwtlv(
            @WebParam(name = "arg0", targetNamespace = "")
                    String arg0,
            @WebParam(name = "arg1", targetNamespace = "")
                    String arg1,
            @WebParam(name = "arg2", targetNamespace = "")
                    String arg2);

    */
/**
     *
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     *//*

    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findZdfhdx", targetNamespace = "http://webservice.data.com/", className = "com.FindZdfhdx")
    @ResponseWrapper(localName = "findZdfhdxResponse", targetNamespace = "http://webservice.data.com/", className = "com.FindZdfhdxResponse")
    @Action(input = "http://webservice.data.com/ZhsfService/findZdfhdxRequest", output = "http://webservice.data.com/ZhsfService/findZdfhdxResponse")
    public String findZdfhdx(
            @WebParam(name = "arg0", targetNamespace = "")
                    String arg0,
            @WebParam(name = "arg1", targetNamespace = "")
                    String arg1,
            @WebParam(name = "arg2", targetNamespace = "")
                    String arg2);

    */
/**
     *
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     *//*

    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findWatergate", targetNamespace = "http://webservice.data.com/", className = "com.FindWatergate")
    @ResponseWrapper(localName = "findWatergateResponse", targetNamespace = "http://webservice.data.com/", className = "com.FindWatergateResponse")
    @Action(input = "http://webservice.data.com/ZhsfService/findWatergateRequest", output = "http://webservice.data.com/ZhsfService/findWatergateResponse")
    public String findWatergate(
            @WebParam(name = "arg0", targetNamespace = "")
                    String arg0,
            @WebParam(name = "arg1", targetNamespace = "")
                    String arg1,
            @WebParam(name = "arg2", targetNamespace = "")
                    String arg2);

    */
/**
     *
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     *//*

    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findReservoir", targetNamespace = "http://webservice.data.com/", className = "com.FindReservoir")
    @ResponseWrapper(localName = "findReservoirResponse", targetNamespace = "http://webservice.data.com/", className = "com.FindReservoirResponse")
    @Action(input = "http://webservice.data.com/ZhsfService/findReservoirRequest", output = "http://webservice.data.com/ZhsfService/findReservoirResponse")
    public String findReservoir(
            @WebParam(name = "arg0", targetNamespace = "")
                    String arg0,
            @WebParam(name = "arg1", targetNamespace = "")
                    String arg1,
            @WebParam(name = "arg2", targetNamespace = "")
                    String arg2);

    */
/**
     *
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     *//*

    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findPump", targetNamespace = "http://webservice.data.com/", className = "com.FindPump")
    @ResponseWrapper(localName = "findPumpResponse", targetNamespace = "http://webservice.data.com/", className = "com.FindPumpResponse")
    @Action(input = "http://webservice.data.com/ZhsfService/findPumpRequest", output = "http://webservice.data.com/ZhsfService/findPumpResponse")
    public String findPump(
            @WebParam(name = "arg0", targetNamespace = "")
                    String arg0,
            @WebParam(name = "arg1", targetNamespace = "")
                    String arg1,
            @WebParam(name = "arg2", targetNamespace = "")
                    String arg2);

    */
/**
     *
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     *//*

    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findSeawall", targetNamespace = "http://webservice.data.com/", className = "com.FindSeawall")
    @ResponseWrapper(localName = "findSeawallResponse", targetNamespace = "http://webservice.data.com/", className = "com.FindSeawallResponse")
    @Action(input = "http://webservice.data.com/ZhsfService/findSeawallRequest", output = "http://webservice.data.com/ZhsfService/findSeawallResponse")
    public String findSeawall(
            @WebParam(name = "arg0", targetNamespace = "")
                    String arg0,
            @WebParam(name = "arg1", targetNamespace = "")
                    String arg1,
            @WebParam(name = "arg2", targetNamespace = "")
                    String arg2);

    */
/**
     *
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     *//*

    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findRctminf", targetNamespace = "http://webservice.data.com/", className = "com.FindRctminf")
    @ResponseWrapper(localName = "findRctminfResponse", targetNamespace = "http://webservice.data.com/", className = "com.FindRctminfResponse")
    @Action(input = "http://webservice.data.com/ZhsfService/findRctminfRequest", output = "http://webservice.data.com/ZhsfService/findRctminfResponse")
    public String findRctminf(
            @WebParam(name = "arg0", targetNamespace = "")
                    String arg0,
            @WebParam(name = "arg1", targetNamespace = "")
                    String arg1,
            @WebParam(name = "arg2", targetNamespace = "")
                    String arg2);

    */
/**
     *
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     *//*

    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findZdfhdxCount", targetNamespace = "http://webservice.data.com/", className = "com.FindZdfhdxCount")
    @ResponseWrapper(localName = "findZdfhdxCountResponse", targetNamespace = "http://webservice.data.com/", className = "com.FindZdfhdxCountResponse")
    @Action(input = "http://webservice.data.com/ZhsfService/findZdfhdxCountRequest", output = "http://webservice.data.com/ZhsfService/findZdfhdxCountResponse")
    public String findZdfhdxCount(
            @WebParam(name = "arg0", targetNamespace = "")
                    String arg0,
            @WebParam(name = "arg1", targetNamespace = "")
                    String arg1,
            @WebParam(name = "arg2", targetNamespace = "")
                    String arg2);

    */
/**
     *
     * @param arg3
     * @param arg2
     * @param arg4
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     *//*

    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findZhdt", targetNamespace = "http://webservice.data.com/", className = "com.FindZhdt")
    @ResponseWrapper(localName = "findZhdtResponse", targetNamespace = "http://webservice.data.com/", className = "com.FindZhdtResponse")
    @Action(input = "http://webservice.data.com/ZhsfService/findZhdtRequest", output = "http://webservice.data.com/ZhsfService/findZhdtResponse")
    public String findZhdt(
            @WebParam(name = "arg0", targetNamespace = "")
                    String arg0,
            @WebParam(name = "arg1", targetNamespace = "")
                    String arg1,
            @WebParam(name = "arg2", targetNamespace = "")
                    String arg2,
            @WebParam(name = "arg3", targetNamespace = "")
                    String arg3,
            @WebParam(name = "arg4", targetNamespace = "")
                    String arg4);

    */
/**
     *
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     *//*

    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findDzzhyhd", targetNamespace = "http://webservice.data.com/", className = "com.FindDzzhyhd")
    @ResponseWrapper(localName = "findDzzhyhdResponse", targetNamespace = "http://webservice.data.com/", className = "com.FindDzzhyhdResponse")
    @Action(input = "http://webservice.data.com/ZhsfService/findDzzhyhdRequest", output = "http://webservice.data.com/ZhsfService/findDzzhyhdResponse")
    public String findDzzhyhd(
            @WebParam(name = "arg0", targetNamespace = "")
                    String arg0,
            @WebParam(name = "arg1", targetNamespace = "")
                    String arg1,
            @WebParam(name = "arg2", targetNamespace = "")
                    String arg2);

    */
/**
     *
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     *//*

    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findZdfyfxd", targetNamespace = "http://webservice.data.com/", className = "com.FindZdfyfxd")
    @ResponseWrapper(localName = "findZdfyfxdResponse", targetNamespace = "http://webservice.data.com/", className = "com.FindZdfyfxdResponse")
    @Action(input = "http://webservice.data.com/ZhsfService/findZdfyfxdRequest", output = "http://webservice.data.com/ZhsfService/findZdfyfxdResponse")
    public String findZdfyfxd(
            @WebParam(name = "arg0", targetNamespace = "")
                    String arg0,
            @WebParam(name = "arg1", targetNamespace = "")
                    String arg1,
            @WebParam(name = "arg2", targetNamespace = "")
                    String arg2);

    */
/**
     *
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     *//*

    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findRiver", targetNamespace = "http://webservice.data.com/", className = "com.FindRiver")
    @ResponseWrapper(localName = "findRiverResponse", targetNamespace = "http://webservice.data.com/", className = "com.FindRiverResponse")
    @Action(input = "http://webservice.data.com/ZhsfService/findRiverRequest", output = "http://webservice.data.com/ZhsfService/findRiverResponse")
    public String findRiver(
            @WebParam(name = "arg0", targetNamespace = "")
                    String arg0,
            @WebParam(name = "arg1", targetNamespace = "")
                    String arg1,
            @WebParam(name = "arg2", targetNamespace = "")
                    String arg2);

    */
/**
     *
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     *//*

    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findAreaCount", targetNamespace = "http://webservice.data.com/", className = "com.FindAreaCount")
    @ResponseWrapper(localName = "findAreaCountResponse", targetNamespace = "http://webservice.data.com/", className = "com.FindAreaCountResponse")
    @Action(input = "http://webservice.data.com/ZhsfService/findAreaCountRequest", output = "http://webservice.data.com/ZhsfService/findAreaCountResponse")
    public String findAreaCount(
            @WebParam(name = "arg0", targetNamespace = "")
                    String arg0,
            @WebParam(name = "arg1", targetNamespace = "")
                    String arg1,
            @WebParam(name = "arg2", targetNamespace = "")
                    String arg2);

    */
/**
     *
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     *//*

    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findErnyctrinf", targetNamespace = "http://webservice.data.com/", className = "com.FindErnyctrinf")
    @ResponseWrapper(localName = "findErnyctrinfResponse", targetNamespace = "http://webservice.data.com/", className = "com.FindErnyctrinfResponse")
    @Action(input = "http://webservice.data.com/ZhsfService/findErnyctrinfRequest", output = "http://webservice.data.com/ZhsfService/findErnyctrinfResponse")
    public String findErnyctrinf(
            @WebParam(name = "arg0", targetNamespace = "")
                    String arg0,
            @WebParam(name = "arg1", targetNamespace = "")
                    String arg1,
            @WebParam(name = "arg2", targetNamespace = "")
                    String arg2);

    */
/**
     *
     * @param arg3
     * @param arg2
     * @param arg4
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     *//*

    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findFybs", targetNamespace = "http://webservice.data.com/", className = "com.FindFybs")
    @ResponseWrapper(localName = "findFybsResponse", targetNamespace = "http://webservice.data.com/", className = "com.FindFybsResponse")
    @Action(input = "http://webservice.data.com/ZhsfService/findFybsRequest", output = "http://webservice.data.com/ZhsfService/findFybsResponse")
    public String findFybs(
            @WebParam(name = "arg0", targetNamespace = "")
                    String arg0,
            @WebParam(name = "arg1", targetNamespace = "")
                    String arg1,
            @WebParam(name = "arg2", targetNamespace = "")
                    String arg2,
            @WebParam(name = "arg3", targetNamespace = "")
                    String arg3,
            @WebParam(name = "arg4", targetNamespace = "")
                    String arg4);

}
*/
