
package com.ruoyi.web.controller.tool.entity.webServiceUtils;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "zhsfService", targetNamespace = "http://webservice.data.com/", wsdlLocation = "http://10.253.135.46:8070/zhsfService?wsdl")
public class ZhsfService_Service
    extends Service
{

    private final static URL ZHSFSERVICE_WSDL_LOCATION;
    private final static WebServiceException ZHSFSERVICE_EXCEPTION;
    private final static QName ZHSFSERVICE_QNAME = new QName("http://webservice.data.com/", "zhsfService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://10.253.135.46:8070/zhsfService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        ZHSFSERVICE_WSDL_LOCATION = url;
        ZHSFSERVICE_EXCEPTION = e;
    }

    public ZhsfService_Service() {
        super(__getWsdlLocation(), ZHSFSERVICE_QNAME);
    }

    public ZhsfService_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), ZHSFSERVICE_QNAME, features);
    }

    public ZhsfService_Service(URL wsdlLocation) {
        super(wsdlLocation, ZHSFSERVICE_QNAME);
    }

    public ZhsfService_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, ZHSFSERVICE_QNAME, features);
    }

    public ZhsfService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ZhsfService_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ZhsfService
     */
    @WebEndpoint(name = "ZhsfServicePort")
    public ZhsfService getZhsfServicePort() {
        return super.getPort(new QName("http://webservice.data.com/", "ZhsfServicePort"), ZhsfService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ZhsfService
     */
    @WebEndpoint(name = "ZhsfServicePort")
    public ZhsfService getZhsfServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://webservice.data.com/", "ZhsfServicePort"), ZhsfService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (ZHSFSERVICE_EXCEPTION!= null) {
            throw ZHSFSERVICE_EXCEPTION;
        }
        return ZHSFSERVICE_WSDL_LOCATION;
    }

}
